[phases.setup]
nixPkgs = ['nodejs_20']

[phases.build]
# Make VITE_ environment variables available during build
dependsOn = ['setup']
cmds = ['npm install', 'npm run build']

[start]
cmd = 'npm start'

# Explicitly pass VITE_ environment variables to the build phase
[variables]
VITE_SUPABASE_URL = '$VITE_SUPABASE_URL'
VITE_SUPABASE_ANON_KEY = '$VITE_SUPABASE_ANON_KEY'
